name: first-workflow
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    # step 1
      - run: pwd
        name: "Print current directory"

    # step 2
      - run: echo "Hello World. This is my first CI workflow _____ test"
        name: test2
