name: upload art
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: touch file.txt && echo "this is test file" >> file.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: file.txt
